### ISSUE TITLE
Thanks, but no cigar..

### ISSUE THREAD

**Issue by menuman** [therealmko/zilliqastats#2]
Friend, thanks for updating your script but I cannot get the syntax right. It tries but keeps returning the help and optional arguments. If you have time please take a peak. Thanks
<img width="2560" alt="screen shot" src="https://user-images.githubusercontent.com/46523158/50972797-81278e00-14b5-11e9-8a73-f38c9d2cb1e6.png">

**Comment by therealmko** [comment]
Try this:
$ ./zilliqastats.py -o total -l zilliqa-00001-log.txt

No need to execute with python3 in front normally as script sources it from the environment.
Option can be: total, daytotal or epochstats

Alternatively just run $ ./zilliqastats.py 
It will use defaults "total" for option and "zilliqa-00001-log.txt" for logfile name.

**Comment by menuman** [comment]
Friend, If I am bothering you please let me know. I dont want to. But if you are willing here is the latest returns. It will not run without python3, I have all the files, but still getting errors. Again, it sounds great but it not that important if it takes too much of 
your time. Thanks, Donald P. Burns
<img width="2560" alt="screen shot 2" src="https://user-images.githubusercontent.com/46523158/50976001-e16dfe00-14bc-11e9-8681-e8dc3f64162e.png">

**Comment by therealmko** [comment]
No problem, just don't have a quick solution atm. Seems you only have python v3 and not v2.7 or something else in the v2.x range. As that is what I am using wrote it for the 2.x version of Python.

This is my setup:
$ which python
/usr/bin/python
$ python -V
Python 2.7.12
$ 

I don't suppose you have both a 2.x and a 3.x version do you?

**Comment by menuman** [comment]
I am a novice. I downloaded the newest ubuntu for mac on virtual box. I
studied linux a couple semesters years ago. It says python not found, sudo
apt install python3 "You also have python3 installed, you can run 'python3'
instead." When I change directory to /usr/bin/ there is only python3 but it
is not a directory. So this python3 is not gonna work but thanks. I will
keep it in mind if I change or find ver2.x. you are great thanks. Don Burns

**Comment by therealmko** [comment]
I have added a zilliqastats.py3 which (hopefully) should work for python v3.

Can you try that one?

**Comment by menuman** [comment]
Thanks, I will. Be about an hour. Thanks so much!

**Comment by therealmko** [comment]
To make it copy / pastable:

$ python3 ./zilliqastats.py3 -o total -l zilliqa-00001-log.txt
$ python3 ./zilliqastats.py3 -o daytotal -l zilliqa-00001-log.txt
$ python3 ./zilliqastats.py3 -o daytotal -l zilliqa-00001-log.txt

**Comment by menuman** [comment]
It worked!! Woo hoo. I have no rewards but it worked. You are the man (or
woman)! By the way, I just started mining zilliqa 2 days ago and left my
machine on 48 hours and nothing has happened no rewards, do you know if I
should have been yet? Does rewards or mining happen in days or hours?
Thanks so much. Don

**Comment by therealmko** [comment]
Good to hear!

Mining goes per Epoch which is roughly 1,5 hours. So at max within 3 hours you can be in. But it could take some time, especially on a laptop with just CPU mining. It is possible though, I am doing so too. Not a lot of miners I think now, made 26 Zil today ;-)

**Comment by menuman** [comment]
Holy crap thats what I want. I am still not working, I know I should have
some. I will keep on it. Thanks for the info. You are the best.

thanks

**Comment by menuman** [comment]
Fantastic, could I ask you another question? I am running the docker and it
is just sitting at my command prompt and it appears nothing is happening,
is this right? Or do you have an indication its working? Its been running
for hours and nothing.  thanks again Don

**Comment by therealmko** [comment]
Not sure if docker implementation is different from native install. But check what you get when going to your join folder and do:

$ tail -f zilliqa-00001-log.txt

It should give you some indication. Too many connection refused and likely a router / port forwarding issue. Just "Round is not running" message means wait till next Epoch to see if you get in.

Could be a lot going on, or not. You can always ask in the Zilliqa mining Telegram group: https://t.me/zilliqaminer

**Comment by menuman** [comment]
Thanks!
